# NumPy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:
NumPy是使用Python进行科学计算的基础软件包。 它包含以下内容：
- a powerful N-dimensional array object
  一个强大的N维数组对象
- sophisticated (broadcasting) functions
  复杂（广播）功能（现在还不是很懂是什么）
- tools for integrating C/C++ and Fortran code
  用于集成C / C ++和Fortran代码的工具
- useful linear algebra, Fourier transform, and random number capabilities
  有用的线性代数，傅里叶变换和随机数能力（这些在后面需要练习）

## 数组功能

In [4]:
import numpy as np

a = np.array([0, 1, 2, 3])

print a


[0 1 2 3]


In [18]:
print np.eye(3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
